Fix `target_name` for multi-subreddit targeting being too long.
They're causing the db to error with:
	sqlalchemy.exc.OperationalError: (OperationalError) index
	row requires 41136 bytes, maximum size is 8191